rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\AlphaTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\AlphaTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CancelTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CancelTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CmdLineTest1\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CmdLineTest1\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CommonLib\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\CommonLib\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ConsoleTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ConsoleTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\Parms\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\Parms\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\PrintTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\PrintTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ProtoTcpServer\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ProtoTcpServer\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ProtoUdp\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ProtoUdp\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\RisLib\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\RisLib\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\Test\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\Test\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadNotify\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadSample\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadSample\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadServices\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadServices\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\ThreadTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\TimerTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\TimerTest\obj
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\TimerThreadTest\bin
rmdir /s /q C:\Prime\DevelopLinux\Dev_RisLibLx\TimerThreadTest\obj
